#!/usr/bin/env bash
# AI Upscaler — Quick Install
# Downloads the Real-ESRGAN Vulkan binary. Works on Linux, macOS, Windows (Git Bash).
set -e

if readlink -f "$0" &>/dev/null; then
    PLUGIN_DIR="$(dirname "$(readlink -f "$0")")"
else
    PLUGIN_DIR="$(cd "$(dirname "$0")" && pwd)"
fi

_select_platform() {
    local options=("Linux" "macOS" "Windows (Git Bash / MSYS2)")
    local values=("linux" "macos" "windows")
    local selected=0
    local count=${#options[@]}

    _redraw() {
        local i
        for i in $(seq 0 $((count - 1))); do
            if [ "$i" -eq "$selected" ]; then
                printf "  \033[7m %s \033[0m\n" "${options[$i]}"
            else
                printf "    %s\n" "${options[$i]}"
            fi
        done
    }

    echo "Select your operating system (use ↑/↓ arrows, Enter to confirm):"
    echo ""
    _redraw

    while true; do
        IFS= read -r -s -n 1 key
        if [ "$key" = $'\033' ]; then
            IFS= read -r -s -n 1 bracket
            IFS= read -r -s -n 1 arrow
            if [ "$bracket" = "[" ]; then
                case "$arrow" in
                    A) [ "$selected" -gt 0 ] && selected=$((selected - 1)) ;;
                    B) [ "$selected" -lt $((count - 1)) ] && selected=$((selected + 1)) ;;
                esac
            fi
            printf "\033[%dA\033[J" "$count"
            _redraw
        elif [ -z "$key" ]; then
            printf "\n\n"
            break
        fi
    done

    PLATFORM="${values[$selected]}"
    echo "  Selected: ${options[$selected]}"
    echo ""
}

_load_env() {
    ENV_FILE="$PLUGIN_DIR/.env"
    if [ -f "$ENV_FILE" ]; then
        . "$ENV_FILE"
        return 0
    fi

    echo ""
    echo "============================================"
    echo " First Time Setup"
    echo "============================================"
    _select_platform

    GIT_BASH_PATH=""
    if [ "$PLATFORM" = "windows" ]; then
        local default_bash="C:/Program Files/Git/bin/bash.exe"
        printf "Git Bash path [%s]: " "$default_bash"
        read -r GIT_BASH_PATH
        if [ -z "$GIT_BASH_PATH" ]; then
            GIT_BASH_PATH="$default_bash"
        fi
    fi

    cat > "$ENV_FILE" << ENVEOF
# AI Plugins Configuration
# Generated by install.sh — edit manually if needed
PLATFORM=$PLATFORM
GIT_BASH_PATH="$GIT_BASH_PATH"
ENVEOF

    echo "[✓] Settings saved to $ENV_FILE"
    . "$ENV_FILE"
}

_load_env

# --- Platform-specific variables ---
case "$PLATFORM" in
    linux)
        GIMP_PLUGINS="$HOME/.config/GIMP/3.2/plug-ins"
        BINARY_URL="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-ubuntu.zip"
        BINARY_NAME="realesrgan-ncnn-vulkan"
        ;;
    macos)
        GIMP_PLUGINS="$HOME/Library/Application Support/GIMP/3.2/plug-ins"
        BINARY_URL="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-macos.zip"
        BINARY_NAME="realesrgan-ncnn-vulkan"
        ;;
    windows)
        GIMP_PLUGINS="$APPDATA/GIMP/3.2/plug-ins"
        GIMP_PLUGINS="$(echo "$GIMP_PLUGINS" | sed 's|\\|/|g' | sed 's|C:|/c|')"
        BINARY_URL="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.5.0/realesrgan-ncnn-vulkan-20220424-windows.zip"
        BINARY_NAME="realesrgan-ncnn-vulkan.exe"
        ;;
esac

PLUGINS_PATH="$GIMP_PLUGINS/ai-upscaler"
BIN_DIR="$PLUGINS_PATH/bin"

echo ""
echo "============================================"
echo " AI Upscaler — Install"
echo "============================================"
echo " Platform: $PLATFORM"
echo ""

# Copy all plugin files
echo "[→] Copying plugin files to $PLUGINS_PATH ..."
mkdir -p "$PLUGINS_PATH"
cp -r "$PLUGIN_DIR/"* "$PLUGINS_PATH/"
find "$PLUGINS_PATH" -name "*.py" -exec chmod +x {} \; 2>/dev/null || true
find "$PLUGINS_PATH" -name "*.sh" -exec chmod +x {} \; 2>/dev/null || true

# Remove pre-bundled Linux binary on non-Linux platforms
if [ "$PLATFORM" != "linux" ]; then
    rm -f "$BIN_DIR/realesrgan-ncnn-vulkan" 2>/dev/null || true
fi

# Download platform-correct binary if not present
if [ ! -f "$BIN_DIR/$BINARY_NAME" ]; then
    echo "[→] Downloading Real-ESRGAN Vulkan binary..."
    mkdir -p "$BIN_DIR"
    if command -v wget &> /dev/null; then
        wget -q "$BINARY_URL" -O /tmp/realesrgan-ncnn.zip
    elif command -v curl &> /dev/null; then
        curl -sL "$BINARY_URL" -o /tmp/realesrgan-ncnn.zip
    else
        echo "[!] wget or curl required. Install one and retry."
        exit 1
    fi
    unzip -oq /tmp/realesrgan-ncnn.zip -d /tmp/realesrgan-extract/
    mv /tmp/realesrgan-extract/$BINARY_NAME "$BIN_DIR/" 2>/dev/null || \
        mv /tmp/realesrgan-extract/realesrgan-ncnn-vulkan "$BIN_DIR/$BINARY_NAME" 2>/dev/null || \
        mv /tmp/realesrgan-extract/realesrgan-ncnn-vulkan.exe "$BIN_DIR/$BINARY_NAME" 2>/dev/null
    mv /tmp/realesrgan-extract/models "$BIN_DIR/" 2>/dev/null || true
    chmod +x "$BIN_DIR/$BINARY_NAME" 2>/dev/null || true
    rm -rf /tmp/realesrgan-ncnn.zip /tmp/realesrgan-extract
    echo "[✓] Binary installed"
else
    echo "[✓] Binary already installed"
fi

# Check Vulkan driver
echo ""
if command -v vulkaninfo &> /dev/null; then
    echo "[✓] Vulkan driver found:"
    vulkaninfo --summary 2>/dev/null | grep -i "deviceName\|apiVersion\|driverVersion" || true
elif command -v vulkaninfo64 &> /dev/null; then
    echo "[✓] Vulkan driver found (vulkaninfo64)"
else
    echo "[i] vulkaninfo not installed. Cannot verify Vulkan driver."
    echo "    If the binary fails, install Vulkan drivers for your GPU:"
    echo "    NVIDIA: nvidia.com/drivers"
    echo "    AMD:    amd.com/support (or mesa-vulkan-drivers on Linux)"
    echo "    Intel:  mesa-vulkan-drivers (Linux) / intel.com (Windows)"
    echo "    macOS:  MoltenVK is bundled with the binary (no extra install needed)"
fi

# Flatpak permission (Linux only)
if [ "$PLATFORM" = "linux" ] && command -v flatpak &> /dev/null && flatpak info org.gimp.GIMP &> /dev/null 2>/dev/null; then
    flatpak override --user --talk-name=org.freedesktop.Flatpak org.gimp.GIMP 2>/dev/null || true
fi

echo ""
echo "[✓] Installed to $PLUGINS_PATH"
echo ""
echo "Restart GIMP → AI → Upscaler"
